# Generated by Django 5.0.6 on 2024-07-05 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hatemodel", "0005_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="classification",
            field=models.CharField(
                choices=[(1, "Hate speech detected"), (0, "No hate speech detected")],
                max_length=25,
            ),
        ),
    ]
