# Generated by Django 5.0.6 on 2024-07-05 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hatemodel", "0004_alter_prediction_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=500)),
                ("remarks", models.TextField(blank=True, max_length=200)),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("HS", "Hate speech detected"),
                            ("NHS", "No hate speech detected"),
                        ],
                        max_length=25,
                    ),
                ),
            ],
        ),
    ]
